"""Falsification audit — claim: "we are now ready to plan the coordinate-grounding epic."

Generated by /falsify (2026-06-13). Scope: readiness-to-PLAN the epic (ADR-060/061 + the
`2026-06-11_coordinate_grounding_dossier`), NOT whether coordinates help (that is ADR-061 §5's
experiment). Each test encodes a falsification found during the audit.

Post-amendment state (2026-06-13): P3 + P6 are GREEN — the dossier roadmap was amended to
declare the disk budget + enumerate the seam scope / C-142 prerequisite — they now stand as
regression guards. **P4 (C-142) closed by #106** and **P5 (C-155) closed by #107** — both now
green guards. **P1 remains the one open** *implementation* gate (the static-channel seam code),
marked ``xfail`` per the repo convention for known-open falsification gaps; it flips to XPASS when
#108 lands the seam (tracked as C-153).
"""

import re
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
DOSSIER = REPO / "reports" / "2026-06-11_coordinate_grounding_dossier"
VIOLET = (
    REPO.parent / "views-models" / "models" / "violet_visitor"
)  # sibling repo; adjust if relocated


# --- P1 (soft): the rollout/training feedback hard-assumes input_channels == output channels ----
@pytest.mark.xfail(
    reason="C-153: static-channel seam not yet built into the inference/training feedback path "
    "(epic box 1). XPASS when the seam lands.",
    strict=False,
)
def test_p1_inference_loop_supports_static_input_channels():
    """FALSIFICATION P1. `HydraNetInference.predict()` builds the seed input from
    `config["features"]` and feeds the 3-channel prediction *directly* back as the next input
    (`t0_autoreg = t1_pred`). It has no notion of static (input-only) channels, and ADR-060 says
    coords are NOT in `features`. So input_channels=5 / output_channels=3 cannot run without a new
    seam that (a) injects static channels into the seed input and (b) re-appends them every
    autoregressive step (ADR-060 I3). The same coupling exists in the scheduled-sampling training
    feedback (ADR-056 `_process_sequence`). Turns GREEN when the static-channel seam exists.
    """
    from views_hydranet.utils import hydranet_inference as hi

    src = Path(hi.__file__).read_text()
    has_static_seam = any(
        tok in src for tok in ("static_channel", "static_channels", "_assemble_static")
    )
    assert has_static_seam, (
        "predict() has no static-channel seam: the rollout feeds back only the predicted dynamic "
        "channels and slices the seed input from config['features']. ADR-060/061's input>output "
        "design is not implementable here without new code touching the inference AND training "
        "feedback paths — this is more than the 'Q1 to confirm' the ADRs portray."
    )


# --- P3 (soft): epic plan declares no disk/compute budget despite a precedented truncation ---
def test_p3_epic_plan_declares_disk_budget():
    """FALSIFICATION P3. One prediction dir = ~2.5 GB; the 6-run baseline sweep ALREADY hit
    disk-full and truncated S3_seed4's eval; the disk is ~97% full. A >=2-seed coords-vs-baseline
    campaign with diagnostics needs an explicit disk budget / cleanup step. The roadmap omits it.
    Turns GREEN when 04_roadmap (or 03_harness) states a disk/compute budget + headroom guard.
    """
    text = ""
    for name in ("04_roadmap.md", "03_harness_and_invariants.md"):
        p = DOSSIER / name
        if p.exists():
            text += p.read_text().lower()
    mentions_budget = any(
        k in text for k in ("disk", "gb free", "headroom", "compute budget", "storage")
    )
    assert mentions_budget, (
        "No disk/compute budget in the epic roadmap, yet the identical workflow already truncated "
        "a baseline run (S3_seed4) on disk-full and the volume is at ~97%. Add a budget + guard."
    )


# --- P4 (was HARD): boundedness/explosion-check validated for count-space — CLOSED by #106 -------
def test_p4_explosion_check_validated_for_count_space():
    """CLOSED by #106 (C-142). The explosion-check now composes `log1p(E[y])` like inference via
    `free_running_attractor(emit_fn=...)` — it measures what the hurdle-NB rollout feeds back,
    not count-space `mu` against the log-space bound. The behavioural count-space validation
    (in-range count not mis-flagged; composed-E[y] runaway flagged) lives in
    `tests/test_rollout_stability_guard.py`; now a green regression guard on that closure."""
    import inspect

    from views_hydranet.utils.rollout_diagnostics import free_running_attractor

    assert "emit_fn" in inspect.signature(free_running_attractor).parameters, (
        "the explosion-check probe must accept emit_fn to compose the hurdle-NB feedback (C-142)"
    )
    guard = (REPO / "tests" / "test_rollout_stability_guard.py").read_text()
    assert "hurdle_inrange_count_not_falsely_flagged" in guard, (
        "missing the count-space in-range validation case (C-142)"
    )
    assert "hurdle_expansive_eymean_is_flagged" in guard, (
        "missing the count-space runaway validation case (C-142)"
    )


# --- P5 (was soft): baseline comparator unambiguous — CLOSED by #107 (C-155) -------------------
_KNOWN_LOSSES = ("hurdle_nb", "tobit", "lognormal_nll", "basu_dpd", "standard")


def _loss_reg_of(text: str) -> str | None:
    """First known loss name appearing after a `loss_reg` key — format-agnostic across the direct
    (`'loss_reg': 'hurdle_nb'`) and wandb-sweep (`'loss_reg': {'value': 'hurdle_nb'}`) layouts."""
    m = re.search(r"loss_reg.*?(" + "|".join(_KNOWN_LOSSES) + r")", text, re.S)
    return m.group(1) if m else None


def test_p5_baseline_config_unambiguous():
    """CLOSED by #107 (C-155). The one-variable test compares +coords vs the hurdle-NB baseline; I5
    needs 'bit-identical when off', so the two violet configs must not disagree on the loss. The
    stale `config_sweep.py` (tobit/focal) was aligned to the canonical `config_hyperparameters.py`,
    so a sweep can't silently benchmark against Tobit. Green guard that they agree on `loss_reg`
    (provenance pinned in dossier `05`; clamp confirmed off)."""
    cfg_dir = VIOLET / "configs"
    if not cfg_dir.exists():
        pytest.skip(f"violet_visitor configs not found at {cfg_dir} (sibling-repo path)")
    hyper_loss = _loss_reg_of((cfg_dir / "config_hyperparameters.py").read_text())
    sweep_loss = _loss_reg_of((cfg_dir / "config_sweep.py").read_text())
    assert hyper_loss and sweep_loss and hyper_loss == sweep_loss, (
        f"Baseline config is ambiguous: hyperparameters loss_reg={hyper_loss} vs "
        f"sweep loss_reg={sweep_loss}. Align the stale sweep config before the one-variable test."
    )


# --- P6 (soft, adequacy): roadmap treats plan-prerequisites as deferred build details ---
def test_p6_roadmap_enumerates_seam_scope_and_prereqs():
    """FALSIFICATION P6 (adequacy). Roadmap box 1 ('implement the ADR-060 seam') must enumerate the
    cross-cutting scope the audit surfaced — the inference AND training feedback paths, the
    coords-not-in-`features` resolution, the FeatureScaler bypass — and the C-142 + disk
    prerequisites (P3/P4). Turns GREEN when 04_roadmap names these explicitly.
    """
    roadmap = (DOSSIER / "04_roadmap.md").read_text().lower()
    needs = {
        "rollout/training feedback path": ("feedback" in roadmap or "rollout loop" in roadmap),
        "explosion-check / C-142 prereq": ("c-142" in roadmap or "explosion-check" in roadmap),
        "disk/compute budget": ("disk" in roadmap or "headroom" in roadmap),
    }
    missing = [k for k, ok in needs.items() if not ok]
    assert not missing, f"Roadmap box 1 omits plan-prerequisites: {missing}"
