"""
Falsification test stubs for claim:
"The root cause is: data differences cause divergent predictions through
two compounding mechanisms — (1) different cell values in early windows
(steps 0-114), and (2) different window locations in later training
(steps 115+). The second mechanism is the dominant one, affecting 75%
of training."

Generated by /falsify audit on 2026-05-26

Hard falsification F3 and soft falsification F1 found.
These tests encode the falsifying observations.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

MODELS_ROOT = Path(__file__).resolve().parents[1].parent / "views-models" / "models"
PA_PARQUET = MODELS_ROOT / "purple_alien" / "data" / "raw" / "calibration_viewser_df.parquet"
BS_PARQUET = MODELS_ROOT / "bright_starship" / "data" / "raw" / "calibration_datafactory_df.parquet"
EVENT_COLS = ["lr_sb_best", "lr_ns_best", "lr_os_best"]

CONFIG = {
    "time_col": "month_id",
    "id_col": "priogrid_gid",
    "spatial_cols": ["row", "col"],
    "identity_cols": ["month_id", "priogrid_gid", "c_id", "row", "col"],
    "features": ["lr_sb_best", "lr_ns_best", "lr_os_best"],
    "index_names": ["month_id", "priogrid_gid"],
    "input_channels": 3,
    "row_offset": 87,
    "col_offset": 310,
    "height": 180,
    "width": 180,
    "window_dim": 32,
    "np_seed": 4,
    "total_lessons": 150,
    "windows_per_lesson": 3,
    "max_ratio": 0.95,
    "min_ratio": 0.05,
    "slope_ratio": 0.75,
    "roof_ratio": 0.7,
    "min_events": 5,
    "steps": list(range(1, 37)),
    "transformations": {
        "log1p": ["lr_sb_best", "lr_ns_best", "lr_os_best"],
        "asinh": [],
        "identity": [],
    },
    "derivations": {
        "binary": [
            {"from": "lr_sb_best", "to": "by_sb_best", "threshold": 0},
            {"from": "lr_ns_best", "to": "by_ns_best", "threshold": 0},
            {"from": "lr_os_best", "to": "by_os_best", "threshold": 0},
        ],
    },
}


def _skip_if_no_data():
    if not PA_PARQUET.exists() or not BS_PARQUET.exists():
        pytest.skip("Calibration parquets not available")


def _build_volumes():
    from views_hydranet.utils.data_fetcher import DataFetcher
    from views_hydranet.utils.volume_handler import VolumeHandler

    _skip_if_no_data()

    dfs = {}
    for label, path in [("pa", PA_PARQUET), ("bs", BS_PARQUET)]:
        df = pd.read_parquet(path).reset_index()
        df = df.sort_values(["month_id", "priogrid_gid"])
        df = df[df["priogrid_gid"] > 0].copy()
        df = DataFetcher.apply_blueprint(df, CONFIG)
        for col in EVENT_COLS:
            df[col] = np.log1p(df[col])
        dfs[label] = VolumeHandler.from_df(df, CONFIG)
    return dfs["pa"], dfs["bs"]


def test_falsify_f3_75_percent_claim():
    """
    Probe F3 (Category E — Consistency): The claim states mechanism B affects
    "75% of training." The actual fraction of steps with different busy_cell
    sets is 45.56% (205/450), not 75%.

    The "75%" conflates "steps occurring after the first divergence point"
    (335/450 = 74.4%) with "steps that actually have different window
    locations." 130 of those 335 post-boundary steps have identical
    busy_cell sets.

    Severity: Hard falsification.

    Expected: The fraction of steps with different busy_cell sets should be
    >= 70% for the "75%" claim to be approximately correct.
    """
    from views_hydranet.utils.curriculum import CurriculumLearner

    pa_vh, bs_vh = _build_volumes()
    pa_cl = CurriculumLearner(CONFIG, pa_vh)
    bs_cl = CurriculumLearner(CONFIG, bs_vh)

    steps_len = len(CONFIG["steps"])
    pa_train = pa_vh.slice_time(0, pa_vh.data.shape[pa_vh.get_axis_idx("T")] - steps_len)
    bs_train = bs_vh.slice_time(0, bs_vh.data.shape[bs_vh.get_axis_idx("T")] - steps_len)

    total_steps = CONFIG["total_lessons"] * CONFIG["windows_per_lesson"]
    n_divergent = 0

    for step in range(total_steps):
        pa_subj, pa_thresh = pa_cl.get_lesson(step)
        bs_subj, bs_thresh = bs_cl.get_lesson(step)

        pa_idx = pa_train.channel_map.index(pa_subj)
        bs_idx = bs_train.channel_map.index(bs_subj)

        pa_activity = np.count_nonzero(pa_train.data[..., pa_idx], axis=0)
        bs_activity = np.count_nonzero(bs_train.data[..., bs_idx], axis=0)

        pa_cells = set(map(tuple, np.argwhere(pa_activity >= pa_thresh)))
        bs_cells = set(map(tuple, np.argwhere(bs_activity >= bs_thresh)))

        if pa_cells != bs_cells:
            n_divergent += 1

    pct_divergent = 100.0 * n_divergent / total_steps

    assert pct_divergent >= 70.0, (
        f"Only {pct_divergent:.1f}% of steps ({n_divergent}/{total_steps}) have "
        f"different busy_cell sets. The claim '75% of training' is falsified — "
        f"the actual figure is {pct_divergent:.1f}%. "
        f"The diagnostic conflated 'steps after first divergence' with "
        f"'steps that actually diverge.'"
    )


def test_falsify_f1_phase_b_intermittency():
    """
    Probe F1 (Category C — Boundary): The claim treats Phase B (steps 115+)
    as monolithically "different windows." In reality, 38.8% of Phase B steps
    (130/335) have identical busy_cell sets.

    Severity: Soft falsification.

    Expected: If Phase B is a genuine phase of "different window locations,"
    at least 90% of its steps should actually have different busy_cell sets.
    """
    from views_hydranet.utils.curriculum import CurriculumLearner

    pa_vh, bs_vh = _build_volumes()
    pa_cl = CurriculumLearner(CONFIG, pa_vh)
    bs_cl = CurriculumLearner(CONFIG, bs_vh)

    steps_len = len(CONFIG["steps"])
    pa_train = pa_vh.slice_time(0, pa_vh.data.shape[pa_vh.get_axis_idx("T")] - steps_len)
    bs_train = bs_vh.slice_time(0, bs_vh.data.shape[bs_vh.get_axis_idx("T")] - steps_len)

    total_steps = CONFIG["total_lessons"] * CONFIG["windows_per_lesson"]

    # Find first divergence to define Phase B boundary
    first_divergence = None
    for step in range(total_steps):
        pa_subj, pa_thresh = pa_cl.get_lesson(step)
        bs_subj, bs_thresh = bs_cl.get_lesson(step)

        pa_idx = pa_train.channel_map.index(pa_subj)
        bs_idx = bs_train.channel_map.index(bs_subj)

        pa_activity = np.count_nonzero(pa_train.data[..., pa_idx], axis=0)
        bs_activity = np.count_nonzero(bs_train.data[..., bs_idx], axis=0)

        pa_cells = set(map(tuple, np.argwhere(pa_activity >= pa_thresh)))
        bs_cells = set(map(tuple, np.argwhere(bs_activity >= bs_thresh)))

        if pa_cells != bs_cells and first_divergence is None:
            first_divergence = step

    assert first_divergence is not None, "No divergence found at all"

    # Count identical steps within Phase B
    phase_b_total = 0
    phase_b_identical = 0

    for step in range(first_divergence, total_steps):
        pa_subj, pa_thresh = pa_cl.get_lesson(step)
        bs_subj, bs_thresh = bs_cl.get_lesson(step)

        pa_idx = pa_train.channel_map.index(pa_subj)
        bs_idx = bs_train.channel_map.index(bs_subj)

        pa_activity = np.count_nonzero(pa_train.data[..., pa_idx], axis=0)
        bs_activity = np.count_nonzero(bs_train.data[..., bs_idx], axis=0)

        pa_cells = set(map(tuple, np.argwhere(pa_activity >= pa_thresh)))
        bs_cells = set(map(tuple, np.argwhere(bs_activity >= bs_thresh)))

        phase_b_total += 1
        if pa_cells == bs_cells:
            phase_b_identical += 1

    pct_identical = 100.0 * phase_b_identical / phase_b_total

    assert pct_identical <= 10.0, (
        f"{pct_identical:.1f}% of Phase B steps ({phase_b_identical}/{phase_b_total}) "
        f"have identical busy_cell sets. The 'different window locations' "
        f"characterisation is intermittent, not monolithic — Phase B is not "
        f"a clean phase transition."
    )
