"""
Falsification stubs for matplotlib backend safety (issue #46).

Generated by /falsify audit 2026-05-31.
"""


class TestSoftFalsifications:
    def test_P3_test_memory_fingerprint_sets_agg_backend(self):
        """
        P3: test_memory_fingerprint.py imports matplotlib.pyplot at module
        level without setting Agg backend. Alphabetically collected before
        test_visual_diagnostics.py, locking TkAgg for the pytest session.

        Fix: add matplotlib.use("Agg") before the pyplot import in
        test_memory_fingerprint.py, or set MPLBACKEND in conftest.py.
        """
        import ast
        from pathlib import Path

        source = Path("tests/test_memory_fingerprint.py").read_text()
        tree = ast.parse(source)

        found_use_agg = False
        for node in ast.walk(tree):
            if (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr == "use"
            ):
                if node.args and isinstance(node.args[0], ast.Constant):
                    if node.args[0].value.lower() == "agg":
                        found_use_agg = True

        assert found_use_agg, (
            "test_memory_fingerprint.py imports matplotlib.pyplot without "
            "setting Agg backend first. Add: import matplotlib; "
            "matplotlib.use('Agg') before the pyplot import."
        )

    def test_P1_visual_diagnostics_sets_agg_backend(self):
        """
        P1/P2: visual_diagnostics.py must set Agg backend before importing
        pyplot to prevent tkinter threading crashes in sweep mode.

        Fix: add matplotlib.use("Agg") before line 10 in visual_diagnostics.py.
        """
        import ast
        from pathlib import Path

        source = Path("views_hydranet/utils/visual_diagnostics.py").read_text()
        tree = ast.parse(source)

        found_use_agg = False
        for node in ast.walk(tree):
            if (
                isinstance(node, ast.Call)
                and isinstance(node.func, ast.Attribute)
                and node.func.attr == "use"
            ):
                if node.args and isinstance(node.args[0], ast.Constant):
                    if node.args[0].value.lower() == "agg":
                        found_use_agg = True

        assert found_use_agg, (
            "visual_diagnostics.py must call matplotlib.use('Agg') before "
            "importing pyplot. Without this, sweep mode crashes with "
            "Tcl_AsyncDelete from tkinter GC in worker thread."
        )
