"""
Falsification test stubs for claim: "We have identified all major and medium risks"
Generated by /falsify audit on 2026-04-08

Originally TDD RED state — stubs failed with assert False.
Stubs for resolved concerns (C-21, C-31, C-32) converted to passing verification
tests on 2026-04-10 per test-review recommendation.

Remaining RED stub: C-33 (InferenceOrchestrator sequence violation) — still open.
"""

import ast
import inspect
import logging

import numpy as np
import pytest
import torch

# ─── C-31 (RESOLVED): ADR-008 log-before-raise compliance ───────────────────


def test_falsify_01_adr008_training_forensics_log_before_raise(caplog):
    """Verify C-31: training_forensics.py logs error before raising."""
    from views_hydranet.utils.training_forensics import TrainingForensics

    config = {
        "regression_targets": ["lr_sb"],
        "classification_targets": ["by_sb"],
        "regression_metrics": ["mse"],
        "classification_metrics": ["ap"],
    }
    forensics = TrainingForensics(config)

    # 1. Unknown key in record() → KeyError with logger.error
    with caplog.at_level(logging.ERROR, logger="views_hydranet.utils.training_forensics"):
        with pytest.raises(KeyError, match="not initialized"):
            forensics.record("UNKNOWN:key", torch.zeros(1), torch.zeros(1))
    assert "not initialized" in caplog.text

    caplog.clear()

    # 2. Unknown regression metric → ValueError with logger.error
    with caplog.at_level(logging.ERROR, logger="views_hydranet.utils.training_forensics"):
        with pytest.raises(ValueError, match="Unknown regression metric"):
            forensics._calculate_reg_metric("nonexistent", np.zeros(5), np.zeros(5))
    assert "Unknown regression metric" in caplog.text

    caplog.clear()

    # 3. Unknown classification metric → ValueError with logger.error
    # Need both classes present in y to bypass the single-class guard
    y_both_classes = np.array([0.0, 0.0, 1.0, 1.0, 0.0])
    yh_probs = np.array([0.1, 0.2, 0.8, 0.9, 0.3])
    with caplog.at_level(logging.ERROR, logger="views_hydranet.utils.training_forensics"):
        with pytest.raises(ValueError, match="Unknown classification metric"):
            forensics._calculate_cls_metric("nonexistent", y_both_classes, yh_probs)
    assert "Unknown classification metric" in caplog.text


def test_falsify_01b_adr008_config_initializer_log_before_raise(caplog, valid_config_dict):
    """Verify C-31: HydraNetConfig.__getitem__ logs error before KeyError."""
    from views_hydranet.utils.config_initializer import HydraNetConfig

    config_obj = HydraNetConfig(**valid_config_dict)

    with caplog.at_level(logging.ERROR, logger="views_hydranet.utils.config_initializer"):
        with pytest.raises(KeyError):
            _ = config_obj["this_key_does_not_exist_xyz"]
    assert "not found" in caplog.text


def test_falsify_01c_adr008_volume_handler_log_before_raise(caplog):
    """Verify C-31: VolumeHandler.wrap_predictions() logs error before ValueError."""
    from views_hydranet.utils.volume_handler import VolumeHandler

    data = np.zeros((2, 3, 3, 2), dtype=np.float32)
    handler = VolumeHandler(
        data=data,
        axes=("T", "H", "W", "C"),
        channel_map=["feat_a", "feat_b"],
        time_col="month_id",
        id_col="priogrid_gid",
        spatial_cols=("row", "col"),
        identity_cols=(),
        feature_cols=("feat_a", "feat_b"),
    )

    posterior = np.zeros((2, 3, 3, 1, 4), dtype=np.float32)
    with caplog.at_level(logging.ERROR, logger="views_hydranet.utils.volume_handler"):
        with pytest.raises(ValueError, match="Ledger Corruption"):
            handler.wrap_predictions(posterior, target_names=["feat_a"])
    assert "Ledger Corruption" in caplog.text


def test_falsify_01d_adr008_mtloss_log_before_raise(caplog):
    """Verify C-31: MultiTaskLoss logs error before ValueError on count mismatch."""
    from views_hydranet.utils.mtloss import MultiTaskLoss

    is_regression = torch.Tensor([True, False])
    mtl = MultiTaskLoss(is_regression, reduction="sum")

    wrong_count = torch.tensor([0.1, 0.2, 0.3])
    with caplog.at_level(logging.ERROR, logger="views_hydranet.utils.mtloss"):
        with pytest.raises(ValueError, match="task count mismatch"):
            mtl(wrong_count)
    assert "task count mismatch" in caplog.text


# ─── C-32 (RESOLVED): VolumeSampler CIC failure modes tested ────────────────


def test_falsify_03_volume_sampler_geometric_overflow_untested():
    """Verify C-32: VolumeSampler geometric overflow tests exist."""
    from tests.test_volume_sampler import TestGeometricOverflow

    assert hasattr(TestGeometricOverflow, "test_edge_anchor_produces_valid_window"), (
        "TestGeometricOverflow.test_edge_anchor_produces_valid_window must exist"
    )
    assert hasattr(TestGeometricOverflow, "test_max_dim_produces_single_valid_window"), (
        "TestGeometricOverflow.test_max_dim_produces_single_valid_window must exist"
    )


def test_falsify_03b_volume_sampler_ledger_inconsistency_untested():
    """Verify C-32: VolumeSampler ledger inconsistency is tested."""
    from tests.test_volume_sampler import TestRed

    assert hasattr(TestRed, "test_red_unknown_target"), (
        "TestRed.test_red_unknown_target must exist (covers ledger inconsistency)"
    )


# ─── C-33 (OPEN): InferenceOrchestrator sequence violation ───────────────────


def test_falsify_03c_orchestrator_sequence_enforced_by_composition():
    """
    C-33 verification: InferenceOrchestrator ADR 039 sequence is enforced
    implicitly by method composition — each step's return type is the next
    step's required input type. Bypass is structurally impossible without
    reimplementing the pipeline.

    Verify that _run_inference_pipeline exists and is a single method
    encoding the full Predict→Align→Wrap→Invert→Collapse sequence.
    """
    import inspect

    from views_hydranet.utils.inference_orchestrator import InferenceOrchestrator

    source = inspect.getsource(InferenceOrchestrator._run_inference_pipeline)
    assert "generate_posterior" in source, "Step 1 PREDICT missing"
    assert "slice_time" in source, "Step 2 ALIGN missing"
    assert "wrap_predictions" in source, "Step 3 WRAP missing"
    assert "inverse_transform" in source, "Step 4 INVERT missing"
    assert "collapse_to_point" in source, "Step 5 COLLAPSE missing"


# ─── C-21 (RESOLVED): Bare except Exception compliance ──────────────────────


def test_falsify_06_c21_undercounts_bare_except():
    """
    Verify C-21 resolution: All bare 'except Exception' blocks in production code
    now log at ERROR level per ADR-008 Section 4.
    """
    from views_hydranet.utils import hydranet_inference, visual_diagnostics

    # Both modules must have loggers
    assert hasattr(hydranet_inference, "logger")
    assert hasattr(visual_diagnostics, "logger")

    # VisualDiagnostics must have >= 9 except handlers (the biopsy methods)
    source = inspect.getsource(visual_diagnostics.VisualDiagnostics)
    tree = ast.parse(source)
    except_handlers = [node for node in ast.walk(tree) if isinstance(node, ast.ExceptHandler)]
    assert len(except_handlers) >= 9, (
        f"Expected >= 9 except handlers in VisualDiagnostics, found {len(except_handlers)}"
    )
