"""Falsification stubs — readiness for the "two 8-sample no-coords runs" step.

Generated by /falsify (2026-06-16). Each test encodes a falsification of the claim
*"we are ready to get back on track, starting with two 8-sample runs."* They are RED
until the corresponding fix lands. Do not delete — turn green by fixing.
"""

from pathlib import Path

import pytest

# C-247/F-Z2: platform-relative (NEVER a hardcoded machine path), and skip when the sibling
# views-models repo is absent (CI / fresh clone) — this is a cross-repo deployment check.
# parents[2] = the views_platform dir that holds both views-hydranet and views-models.
VIOLET_CONFIG = (
    Path(__file__).resolve().parents[2]
    / "views-models/models/violet_visitor/configs/config_hyperparameters.py"
)

if not VIOLET_CONFIG.exists():
    pytest.skip(
        "sibling views-models repo absent (CI/clone); cross-repo violet config check (C-247).",
        allow_module_level=True,
    )


def test_violet_config_operating_point_is_8_samples():
    """HARD (P1): the claimed operating point is 8 samples, but the config still pins 3
    (the C-116 memory-probe value). The "two 8-sample runs" would silently run at 3, and
    every metric would be mislabeled "8-sample". Set n_posterior_samples=8 before launching."""
    text = VIOLET_CONFIG.read_text()
    assert "'n_posterior_samples': 8," in text, (
        "config_hyperparameters.py still pins n_posterior_samples=3 (the C-116 probe). "
        "Set it to 8 before the baseline runs, or relabel the operating point."
    )


def test_noise_band_is_within_run_bootstrap_not_run_to_run():
    """C-162 FIXED (#129): the #110 rule now uses mcr_readout's WITHIN-run 95% bootstrap CI
    as the noise band — not a run-to-run Δ_noise (≡0 under the C-119 determinism fix:
    same-seed --saved runs are bit-identical, proven 78/78 y_pred array_equal). Guard that
    the primitive the corrected rule depends on exists (the doc rewrite is the real fix)."""
    mcr_readout = Path(__file__).resolve().parents[1] / "scripts" / "mcr_readout.py"
    assert "_bootstrap_mcr_ci" in mcr_readout.read_text(), (
        "mcr_readout.py must expose the within-run bootstrap-CI primitive the #110 rule relies on"
    )


@pytest.mark.skip(
    reason="runtime gate — verify with one real 8-sample run before trusting 'ready'"
)
def test_8sample_run_completes_without_oom():
    """SOFT (P3): 8 samples is interpolated between 3 (completes) and 16 (OOM-killed at 16.6 GB,
    C-116/#124); the 8-sample eval footprint on a 32 GB box is unverified. 'Ready to run two
    8-sample runs' assumes it fits. Verify empirically (the #110 acceptance gate)."""
    ...
