"""Falsification stubs — readiness for the "two 8-sample no-coords runs" step.

Generated by /falsify (2026-06-16). Each test encodes a falsification of the claim
*"we are ready to get back on track, starting with two 8-sample runs."* They are RED
until the corresponding fix lands. Do not delete — turn green by fixing.
"""

from pathlib import Path

import pytest

VIOLET_CONFIG = Path(
    "/home/simon/Documents/scripts/views_platform/views-models/"
    "models/violet_visitor/configs/config_hyperparameters.py"
)


def test_violet_config_operating_point_is_8_samples():
    """HARD (P1): the claimed operating point is 8 samples, but the config still pins 3
    (the C-116 memory-probe value). The "two 8-sample runs" would silently run at 3, and
    every metric would be mislabeled "8-sample". Set n_posterior_samples=8 before launching."""
    text = VIOLET_CONFIG.read_text()
    assert "'n_posterior_samples': 8," in text, (
        "config_hyperparameters.py still pins n_posterior_samples=3 (the C-116 probe). "
        "Set it to 8 before the baseline runs, or relabel the operating point."
    )


def test_noise_band_is_within_run_bootstrap_not_run_to_run():
    """C-162 FIXED (#129): the #110 decision rule now uses mcr_readout's WITHIN-run 95% bootstrap CI
    as the noise band — not a run-to-run Δ_noise (which is ≡0 under the C-119 determinism fix:
    two same-seed --saved runs are bit-identical, proven 78/78 y_pred np.array_equal). Guard that the
    primitive the corrected rule depends on exists. (The doc rewrite in #110/dossier-05 is the real
    fix, verified by reading those; this guards its code dependency.)"""
    mcr_readout = Path(__file__).resolve().parents[1] / "scripts" / "mcr_readout.py"
    assert "_bootstrap_mcr_ci" in mcr_readout.read_text(), (
        "mcr_readout.py must expose the within-run bootstrap-CI primitive the #110 rule relies on"
    )


@pytest.mark.skip(
    reason="runtime gate — cannot unit-test; verify with one real 8-sample run before trusting 'ready'"
)
def test_8sample_run_completes_without_oom():
    """SOFT (P3): 8 samples is interpolated between 3 (completes) and 16 (OOM-killed at 16.6 GB,
    C-116/#124); the 8-sample eval footprint on a 32 GB box is unverified. 'Ready to run two
    8-sample runs' assumes it fits. Verify empirically (the #110 acceptance gate)."""
    ...
