"""
Falsification test stubs for claim:
"All sampling_strategies are correctly implemented."

Generated by /falsify audit on 2026-05-26

One soft falsification found: power-law strategy overflows with
extreme alpha values due to missing log-space arithmetic.
"""

from __future__ import annotations

import numpy as np

from views_hydranet.utils.sampling_strategies import select_anchor_power_law


def test_falsify_p4_power_law_extreme_alpha_overflow():
    """
    Probe 4 (Category F — Adversarial): Power-law numerical overflow.

    Finding: With sampling_alpha=200 and activity values including 100,
    100**200 overflows float64 to inf. Weights become [finite, ..., inf],
    total = inf, probabilities = [0, ..., NaN]. rng.choice raises
    ValueError: "probabilities contain NaN".

    The overflow threshold is alpha ≈ 137 for max realistic activity (~180).
    The Boltzmann strategy handles the analogous issue correctly using
    log-sum-exp arithmetic; the power-law strategy lacks this protection.

    Severity: Soft falsification.

    Expected: The function should return a valid (r, c) for any
    positive alpha, either by computing weights in log-space
    (alpha * log(activity), then log-sum-exp) or by clamping
    weights to avoid inf.
    """
    H, W = 16, 16
    activity = np.zeros((H, W), dtype=np.int64)
    activity[0:4, 0:4] = 5
    activity[4:8, 0:8] = 50
    activity[0:4, 4:8] = 100

    config = {"sampling_alpha": 200.0}
    rng = np.random.default_rng(42)

    r, c = select_anchor_power_law(activity, 50, 5, rng, config)
    assert 0 <= r < H and 0 <= c < W, f"Expected valid coordinates, got ({r}, {c})"
