"""
Falsification test stubs for claim: "We have identified all major and medium risks"
Generated by /falsify audit on 2026-04-08

Originally TDD RED state — stubs failed with assert False.
Stubs for resolved concerns (C-21, C-31, C-32) converted to passing verification
tests on 2026-04-10 per test-review recommendation.

Remaining RED stub: C-33 (InferenceOrchestrator sequence violation) — still open.
"""

import ast
import inspect
import logging

import numpy as np
import pytest
import torch

# ─── C-31 (RESOLVED): ADR-008 log-before-raise compliance ───────────────────


def test_falsify_01_adr008_training_forensics_log_before_raise(caplog):
    """Verify C-31: training_forensics.py logs error before raising."""
    from views_hydranet.utils.training_forensics import TrainingForensics

    config = {
        "regression_targets": ["lr_sb"],
        "classification_targets": ["by_sb"],
        "regression_metrics": ["mse"],
        "classification_metrics": ["ap"],
    }
    forensics = TrainingForensics(config)

    # 1. Unknown key in record() → KeyError with logger.error
    with caplog.at_level(logging.ERROR, logger="views_hydranet.utils.training_forensics"):
        with pytest.raises(KeyError, match="not initialized"):
            forensics.record("UNKNOWN:key", torch.zeros(1), torch.zeros(1))
    assert "not initialized" in caplog.text

    caplog.clear()

    # 2. Unknown regression metric → ValueError with logger.error
    with caplog.at_level(logging.ERROR, logger="views_hydranet.utils.training_forensics"):
        with pytest.raises(ValueError, match="Unknown regression metric"):
            forensics._calculate_reg_metric("nonexistent", np.zeros(5), np.zeros(5))
    assert "Unknown regression metric" in caplog.text

    caplog.clear()

    # 3. Unknown classification metric → ValueError with logger.error
    # Need both classes present in y to bypass the single-class guard
    y_both_classes = np.array([0.0, 0.0, 1.0, 1.0, 0.0])
    yh_probs = np.array([0.1, 0.2, 0.8, 0.9, 0.3])
    with caplog.at_level(logging.ERROR, logger="views_hydranet.utils.training_forensics"):
        with pytest.raises(ValueError, match="Unknown classification metric"):
            forensics._calculate_cls_metric("nonexistent", y_both_classes, yh_probs)
    assert "Unknown classification metric" in caplog.text


def test_falsify_01b_adr008_config_initializer_log_before_raise(caplog):
    """Verify C-31: HydraNetConfig.__getitem__ logs error before KeyError."""
    from views_hydranet.utils.config_initializer import HydraNetConfig

    # Build inline (can't call fixtures directly)
    config_dict = {
        "model": "HydraBNUNet06_LSTM4",
        "run_type": "validation",
        "steps": list(range(1, 37)),
        "input_channels": 3,
        "output_channels": 1,
        "total_hidden_channels": 32,
        "dropout_rate": 0.125,
        "learning_rate": 0.001,
        "weight_decay": 0.1,
        "windows_per_lesson": 3,
        "scheduler": "WarmupDecay",
        "warmup_steps": 100,
        "total_lessons": 300,
        "n_posterior_samples": 10,
        "loss_reg": "mse",
        "loss_class": "bce",
        "weight_init": "xavier_norm",
        "clip_grad_norm": True,
        "min_events": 5,
        "slope_ratio": 0.75,
        "roof_ratio": 0.7,
        "freeze_h": "hl",
        "np_seed": 4,
        "torch_seed": 4,
        "window_dim": 32,
        "features": ["lr_sb_best", "lr_ns_best", "lr_os_best"],
        "regression_targets": ["lr_sb_best", "lr_ns_best", "lr_os_best"],
        "classification_targets": ["by_sb_best", "by_ns_best", "by_os_best"],
        "identity_cols": ["c_id", "row", "col"],
        "time_col": "month_id",
        "id_col": "priogrid_gid",
        "spatial_cols": ["row", "col"],
        "height": 180,
        "width": 360,
        "index_names": ["month_id", "priogrid_gid"],
        "row_offset": 0,
        "col_offset": 0,
        "max_ratio": 0.9,
        "min_ratio": 0.1,
        "time_steps": 36,
        "evaluation_mode": "point",
        "aggregate_method": "arithmetic_mean",
        "transformations": {
            "log1p": ["lr_sb_best", "lr_ns_best", "lr_os_best"],
            "identity": [],
        },
        "derivations": {
            "binary": [
                {"from": "lr_sb_best", "to": "by_sb_best", "threshold": 0},
                {"from": "lr_ns_best", "to": "by_ns_best", "threshold": 0},
                {"from": "lr_os_best", "to": "by_os_best", "threshold": 0},
            ]
        },
    }

    config_obj = HydraNetConfig(**config_dict)

    with caplog.at_level(logging.ERROR, logger="views_hydranet.utils.config_initializer"):
        with pytest.raises(KeyError):
            _ = config_obj["this_key_does_not_exist_xyz"]
    assert "not found" in caplog.text


def test_falsify_01c_adr008_volume_handler_log_before_raise(caplog):
    """Verify C-31: VolumeHandler.wrap_predictions() logs error before ValueError."""
    from views_hydranet.utils.volume_handler import VolumeHandler

    data = np.zeros((2, 3, 3, 2), dtype=np.float32)
    handler = VolumeHandler(
        data=data,
        axes=("T", "H", "W", "C"),
        channel_map=["feat_a", "feat_b"],
        time_col="month_id",
        id_col="priogrid_gid",
        spatial_cols=("row", "col"),
        identity_cols=(),
        feature_cols=("feat_a", "feat_b"),
    )

    posterior = np.zeros((2, 3, 3, 1, 4), dtype=np.float32)
    with caplog.at_level(logging.ERROR, logger="views_hydranet.utils.volume_handler"):
        with pytest.raises(ValueError, match="Ledger Corruption"):
            handler.wrap_predictions(posterior, target_names=["feat_a"])
    assert "Ledger Corruption" in caplog.text


def test_falsify_01d_adr008_mtloss_log_before_raise(caplog):
    """Verify C-31: MultiTaskLoss logs error before ValueError on count mismatch."""
    from views_hydranet.utils.mtloss import MultiTaskLoss

    is_regression = torch.Tensor([True, False])
    mtl = MultiTaskLoss(is_regression, reduction="sum")

    wrong_count = torch.tensor([0.1, 0.2, 0.3])
    with caplog.at_level(logging.ERROR, logger="views_hydranet.utils.mtloss"):
        with pytest.raises(ValueError, match="task count mismatch"):
            mtl(wrong_count)
    assert "task count mismatch" in caplog.text


# ─── C-32 (RESOLVED): VolumeSampler CIC failure modes tested ────────────────


def test_falsify_03_volume_sampler_geometric_overflow_untested():
    """Verify C-32: VolumeSampler geometric overflow tests exist."""
    from tests.test_volume_sampler import TestGeometricOverflow

    assert hasattr(TestGeometricOverflow, "test_edge_anchor_produces_valid_window"), (
        "TestGeometricOverflow.test_edge_anchor_produces_valid_window must exist"
    )
    assert hasattr(TestGeometricOverflow, "test_max_dim_produces_single_valid_window"), (
        "TestGeometricOverflow.test_max_dim_produces_single_valid_window must exist"
    )


def test_falsify_03b_volume_sampler_ledger_inconsistency_untested():
    """Verify C-32: VolumeSampler ledger inconsistency is tested."""
    from tests.test_volume_sampler import TestRed

    assert hasattr(TestRed, "test_red_unknown_target"), (
        "TestRed.test_red_unknown_target must exist (covers ledger inconsistency)"
    )


# ─── C-33 (OPEN): InferenceOrchestrator sequence violation ───────────────────


def test_falsify_03c_orchestrator_sequence_violation_untested():
    """
    Probe 3 (Category E): CIC failure mode not in register

    Finding: InferenceOrchestrator CIC Section 6 declares "Sequence Violation"
    failure mode (bypass pipeline order). No test verifies this, and the concern
    is registered as C-33.

    Severity: Soft falsification
    """
    assert False, (
        "InferenceOrchestrator 'Sequence Violation' failure mode: untested (C-33 open)"
    )


# ─── C-21 (RESOLVED): Bare except Exception compliance ──────────────────────


def test_falsify_06_c21_undercounts_bare_except():
    """
    Verify C-21 resolution: All bare 'except Exception' blocks in production code
    now log at ERROR level per ADR-008 Section 4.
    """
    from views_hydranet.utils import hydranet_inference, visual_diagnostics

    # Both modules must have loggers
    assert hasattr(hydranet_inference, "logger")
    assert hasattr(visual_diagnostics, "logger")

    # VisualDiagnostics must have >= 9 except handlers (the biopsy methods)
    source = inspect.getsource(visual_diagnostics.VisualDiagnostics)
    tree = ast.parse(source)
    except_handlers = [
        node for node in ast.walk(tree) if isinstance(node, ast.ExceptHandler)
    ]
    assert len(except_handlers) >= 9, (
        f"Expected >= 9 except handlers in VisualDiagnostics, found {len(except_handlers)}"
    )
