"""
Falsification test stubs for claim:
"The curriculum and sampler select identical training windows (same RNG sequence)
for purple_alien and bright_starship across all 450 steps."

Generated by /falsify audit on 2026-05-26

These tests are in TDD RED state -- they FAIL against the current diagnostic.
Fix the diagnostic to address these findings, then re-run /falsify to verify.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

MODELS_ROOT = Path(__file__).resolve().parents[1].parent / "views-models" / "models"
PA_PARQUET = MODELS_ROOT / "purple_alien" / "data" / "raw" / "calibration_viewser_df.parquet"
BS_PARQUET = (
    MODELS_ROOT / "bright_starship" / "data" / "raw" / "calibration_datafactory_df.parquet"
)
EVENT_COLS = ["lr_ged_sb", "lr_ged_ns", "lr_ged_os"]

CONFIG = {
    "time_col": "month_id",
    "id_col": "priogrid_gid",
    "spatial_cols": ["row", "col"],
    "identity_cols": ["month_id", "priogrid_gid", "c_id", "row", "col"],
    "features": ["lr_ged_sb", "lr_ged_ns", "lr_ged_os"],
    "index_names": ["month_id", "priogrid_gid"],
    "input_channels": 3,
    "row_offset": 87,
    "col_offset": 310,
    "height": 180,
    "width": 180,
    "window_dim": 32,
    "np_seed": 4,
    "total_lessons": 150,
    "windows_per_lesson": 3,
    "max_ratio": 0.95,
    "min_ratio": 0.05,
    "slope_ratio": 0.75,
    "roof_ratio": 0.7,
    "min_events": 5,
    "steps": list(range(1, 37)),
    "transformations": {
        "log1p": ["lr_ged_sb", "lr_ged_ns", "lr_ged_os"],
        "asinh": [],
        "identity": [],
    },
    "derivations": {
        "binary": [
            {"from": "lr_ged_sb", "to": "by_sb_best", "threshold": 0},
            {"from": "lr_ged_ns", "to": "by_ns_best", "threshold": 0},
            {"from": "lr_ged_os", "to": "by_os_best", "threshold": 0},
        ],
    },
}


def _skip_if_no_data():
    if not PA_PARQUET.exists() or not BS_PARQUET.exists():
        pytest.skip("Calibration parquets not available")


def _build_volumes():
    from views_hydranet.utils.data_fetcher import DataFetcher
    from views_hydranet.utils.volume_handler import VolumeHandler

    _skip_if_no_data()

    dfs = {}
    for label, path in [("pa", PA_PARQUET), ("bs", BS_PARQUET)]:
        df = pd.read_parquet(path).reset_index()
        df = df.sort_values(["month_id", "priogrid_gid"])
        df = df[df["priogrid_gid"] > 0].copy()
        df = DataFetcher.apply_blueprint(df, CONFIG)
        for col in EVENT_COLS:
            df[col] = np.log1p(df[col])
        dfs[label] = VolumeHandler.from_df(df, CONFIG)
    return dfs["pa"], dfs["bs"]


def test_falsify_01_busy_cell_locations_parity():
    """
    Probe 1 (Category B): Busy-cell coordinate parity across all 450 steps.

    Finding: 49 steps have matching busy_cell counts but DIFFERENT spatial
    coordinates. First divergence at step 115 (lr_ged_ns, threshold 48).
    The VolumeSampler picks a different anchor cell even though the RNG
    produces the same index, because the index maps into a different
    coordinate array.

    Severity: Hard falsification.

    Expected: All 450 steps should have identical busy_cell coordinate sets
    if the claim "identical windows" is true.
    """
    from views_hydranet.utils.curriculum import CurriculumLearner

    pa_vh, bs_vh = _build_volumes()
    pa_cl = CurriculumLearner(CONFIG, pa_vh)
    bs_cl = CurriculumLearner(CONFIG, bs_vh)

    steps_len = len(CONFIG["steps"])
    pa_train = pa_vh.slice_time(0, pa_vh.data.shape[pa_vh.get_axis_idx("T")] - steps_len)
    bs_train = bs_vh.slice_time(0, bs_vh.data.shape[bs_vh.get_axis_idx("T")] - steps_len)

    total_steps = CONFIG["total_lessons"] * CONFIG["windows_per_lesson"]
    location_mismatches = []

    for step in range(total_steps):
        pa_subj, pa_thresh = pa_cl.get_lesson(step)
        bs_subj, bs_thresh = bs_cl.get_lesson(step)

        pa_idx = pa_train.channel_map.index(pa_subj)
        bs_idx = bs_train.channel_map.index(bs_subj)

        pa_activity = np.count_nonzero(pa_train.data[..., pa_idx], axis=0)
        bs_activity = np.count_nonzero(bs_train.data[..., bs_idx], axis=0)

        pa_busy = set(map(tuple, np.argwhere(pa_activity >= pa_thresh)))
        bs_busy = set(map(tuple, np.argwhere(bs_activity >= bs_thresh)))

        if pa_busy != bs_busy:
            location_mismatches.append(step)

    assert len(location_mismatches) == 0, (
        f"Busy-cell coordinate sets differ at {len(location_mismatches)} / {total_steps} steps. "
        f"First divergence at step {location_mismatches[0]}. "
        f"The claim 'identical training windows' is falsified."
    )


def test_falsify_04_full_450_step_count_parity():
    """
    Probe 4 (Category C): Busy-cell count parity for ALL 450 steps.

    Finding: 156 out of 450 steps have different busy_cell counts.
    First mismatch at step 123 (by_sb_best, threshold 126: PA=9, BS=10).
    The original diagnostic only checked 30 steps and missed this entirely.

    Severity: Hard falsification.

    Expected: All 450 steps should have identical busy_cell counts.
    """
    from views_hydranet.utils.curriculum import CurriculumLearner

    pa_vh, bs_vh = _build_volumes()
    pa_cl = CurriculumLearner(CONFIG, pa_vh)
    bs_cl = CurriculumLearner(CONFIG, bs_vh)

    steps_len = len(CONFIG["steps"])
    pa_train = pa_vh.slice_time(0, pa_vh.data.shape[pa_vh.get_axis_idx("T")] - steps_len)
    bs_train = bs_vh.slice_time(0, bs_vh.data.shape[bs_vh.get_axis_idx("T")] - steps_len)

    total_steps = CONFIG["total_lessons"] * CONFIG["windows_per_lesson"]
    count_mismatches = []

    for step in range(total_steps):
        pa_subj, pa_thresh = pa_cl.get_lesson(step)
        bs_subj, bs_thresh = bs_cl.get_lesson(step)

        pa_idx = pa_train.channel_map.index(pa_subj)
        bs_idx = bs_train.channel_map.index(bs_subj)

        pa_activity = np.count_nonzero(pa_train.data[..., pa_idx], axis=0)
        bs_activity = np.count_nonzero(bs_train.data[..., bs_idx], axis=0)

        pa_n = len(np.argwhere(pa_activity >= pa_thresh))
        bs_n = len(np.argwhere(bs_activity >= bs_thresh))

        if pa_n != bs_n:
            count_mismatches.append((step, pa_subj, pa_thresh, pa_n, bs_n))

    assert len(count_mismatches) == 0, (
        f"Busy-cell counts differ at {len(count_mismatches)} / {total_steps} steps. "
        f"First: step {count_mismatches[0][0]}, {count_mismatches[0][1]}, "
        f"thresh={count_mismatches[0][2]}: "
        f"PA={count_mismatches[0][3]}, BS={count_mismatches[0][4]}. "
        f"The diagnostic checked only 30 steps and missed this."
    )
