"""
Falsification stubs for per-target Tobit sigma (issue #44).

Generated by /falsify audit 2026-05-30. Each stub encodes a finding
that must be fixed before the claim "we understand the splash zone"
can be reasserted.
"""

import pytest


class TestHardFalsifications:
    """These MUST be fixed — they represent silent crashes or wrong behavior."""


class TestSoftFalsifications:
    """These SHOULD be fixed — they undermine confidence in the implementation."""

    def test_P5_extra_keys_in_dict_sigma_rejected(self):
        """
        P5: Extra keys in dict sigma (targets NOT in regression_targets)
        are silently accepted. A typo like 'lr_TYPO' passes validation.

        Fix: add `extra = [k for k in sigma if k not in self.regression_targets]`
        check to validate_per_target_sigma.
        """
        from views_hydranet.utils.config_initializer import HydraNetConfig

        base = {
            "run_type": "calibration",
            "features": ["lr_sb", "lr_ns", "lr_os"],
            "regression_targets": ["lr_sb", "lr_ns", "lr_os"],
            "classification_targets": ["by_sb", "by_ns", "by_os"],
            "height": 8,
            "width": 8,
            "index_names": ["month_id", "priogrid_gid"],
            "time_col": "month_id",
            "id_col": "priogrid_gid",
            "spatial_cols": ["row", "col"],
            "row_offset": 0,
            "col_offset": 0,
            "model": "HydraBNUNet06_LSTM4",
            "window_dim": 4,
            "total_hidden_channels": 16,
            "dropout_rate": 0.1,
            "weight_init": "xavier_norm",
            "learning_rate": 0.001,
            "weight_decay": 0.01,
            "windows_per_lesson": 2,
            "scheduler": "plateau",
            "warmup_steps": 5,
            "clip_grad_norm": True,
            "loss_reg": "tobit",
            "loss_reg_sigma": {"lr_sb": 1.0, "lr_ns": 0.75, "lr_os": 0.5, "lr_TYPO": 2.0},
            "loss_class": "bce",
            "total_lessons": 10,
            "n_posterior_samples": 5,
            "np_seed": 42,
            "torch_seed": 42,
            "min_events": 0,
            "slope_ratio": 1.0,
            "roof_ratio": 1.0,
            "max_ratio": 0.9,
            "min_ratio": 0.1,
            "freeze_h": "none",
            "sampling_strategy": "threshold",
            "evaluation_mode": "point",
            "aggregate_method": "arithmetic_mean",
            "prediction_format": "prediction_frame",
            "time_steps": 3,
            "steps": [1, 2, 3],
            "input_channels": 3,
            "output_channels": 1,
            "identity_cols": ["priogrid_gid", "month_id"],
            "transformations": {"log1p": ["lr_sb", "lr_ns", "lr_os"]},
            "derivations": {
                "binary": [
                    {"from": "lr_sb", "to": "by_sb", "threshold": 0},
                    {"from": "lr_ns", "to": "by_ns", "threshold": 0},
                    {"from": "lr_os", "to": "by_os", "threshold": 0},
                ]
            },
        }

        # Should reject extra key 'lr_TYPO'
        with pytest.raises(ValueError, match="lr_TYPO"):
            HydraNetConfig(**base)
