"""
Falsification tests for sweep root cause analysis.

Generated by /falsify audit of claim:
"The two sweep failure modes are caused by unstable hyperparameter
combinations, not by bugs in views-hydranet code."

HARD FALSIFICATION (P2): ADR-028 Section 3 prescribes regression head
output clamping as CRITICAL. Two governance contracts (architectural_contracts.md §4,
evaluation_contract_v1.md §4.1) promise safety clamping at max=20.0 in log-space.
Neither is implemented. expm1 overflows at ~88 (float32) or ~710 (float64).

SOFT FALSIFICATION (P3): ADR-028 Section 2 prescribes LSTM cell-state
clamping at ±50.0. Autoregressive loop logs drift but never clamps or halts
until the post-loop isfinite check fires after all 36 steps.
"""

import numpy as np
import pytest

from views_hydranet.utils.config_initializer import TRANSFORMS


class TestP2ExpmOverflowGuard:
    """P2: expm1 inverse transform has no overflow guard."""

    @pytest.mark.xfail(
        reason=(
            "Known gap: post-inverse overflow guard not yet implemented. "
            "Will be addressed by Tobit loss (issue #36)."
        ),
        strict=True,
    )
    def test_expm1_overflows_at_float32_boundary(self):
        """
        HARD FALSIFICATION: np.expm1 overflows for float32 inputs above ~88.
        The pipeline uses float32 throughout (VolumeHandler.from_df, line 211).
        ADR-028 §3 prescribes clamping at max=15.0 before inverse transform.
        """
        _, inverse = TRANSFORMS["log1p"]
        val = np.float32(89.0)
        result = inverse(val)
        assert np.isfinite(result), (
            f"expm1(float32(89.0)) = {result}. "
            "ADR-028 §3 requires output clamping before inverse transform. "
            "architectural_contracts.md §4 promises clamping at max=20.0 in log-space."
        )

    @pytest.mark.xfail(
        reason=(
            "Known gap: post-inverse overflow guard not yet implemented. "
            "Will be addressed by Tobit loss (issue #36)."
        ),
        strict=True,
    )
    def test_expm1_overflows_at_float64_boundary(self):
        """
        HARD FALSIFICATION: np.expm1 overflows for float64 inputs above ~709.
        IntegrityGuardian ceiling is 1000, which exceeds the float64 overflow boundary.
        """
        _, inverse = TRANSFORMS["log1p"]
        val = np.float64(710.0)
        result = inverse(val)
        assert np.isfinite(result), (
            f"expm1(float64(710.0)) = {result}. "
            "Even in float64, values above 709 overflow. "
            "IntegrityGuardian.PREDICTION_MAGNITUDE_CEILING=1000 allows this."
        )

    def test_sinh_overflow_parity(self):
        """
        Observation: np.sinh (asinh inverse) has similar overflow characteristics.
        """
        _, inverse = TRANSFORMS["asinh"]
        val = np.float32(89.0)
        result = inverse(val)
        assert np.isfinite(result), (
            f"sinh(float32(89.0)) = {result}. asinh inverse has the same overflow class as expm1."
        )


class TestP3AutoregressiveClamping:
    """P3: Autoregressive loop feeds predictions back without magnitude guard."""

    @pytest.mark.xfail(
        run=False,
        reason=(
            "SOFT FALSIFICATION: Requires architectural change (ADR-028 §2). "
            "Detection exists (isfinite at line 337), prevention does not."
        ),
    )
    def test_autoregressive_predictions_are_bounded(self):
        """
        ADR-028 §2 prescribes cell-state clamping at ±50.0.
        ADR-028 §3 prescribes output clamping at max=15.0.
        Neither is implemented. Predictions feed back unclamped.
        """
        pass

    @pytest.mark.xfail(
        run=False,
        reason=(
            "SOFT FALSIFICATION: IntegrityGuardian.monitor() ceiling=1000 "
            "is only called during training, not inference."
        ),
    )
    def test_integrity_guardian_ceiling_enforced_during_inference(self):
        """
        IntegrityGuardian.monitor() (with PREDICTION_MAGNITUDE_CEILING=1000)
        is called from training_engine.py:516 but NOT from hydranet_inference.py.
        During inference, only logging occurs (100/500 thresholds) with no halt
        until post-loop isfinite check at line 337.
        """
        pass
