"""Falsification stubs — readiness for the "two 8-sample no-coords runs" step.

Generated by /falsify (2026-06-16). Each test encodes a falsification of the claim
*"we are ready to get back on track, starting with two 8-sample runs."* They are RED
until the corresponding fix lands. Do not delete — turn green by fixing.
"""

from pathlib import Path

import pytest

VIOLET_CONFIG = Path(
    "/home/simon/Documents/scripts/views_platform/views-models/"
    "models/violet_visitor/configs/config_hyperparameters.py"
)


def test_violet_config_operating_point_is_8_samples():
    """HARD (P1): the claimed operating point is 8 samples, but the config still pins 3
    (the C-116 memory-probe value). The "two 8-sample runs" would silently run at 3, and
    every metric would be mislabeled "8-sample". Set n_posterior_samples=8 before launching."""
    text = VIOLET_CONFIG.read_text()
    assert "'n_posterior_samples': 8," in text, (
        "config_hyperparameters.py still pins n_posterior_samples=3 (the C-116 probe). "
        "Set it to 8 before the baseline runs, or relabel the operating point."
    )


@pytest.mark.xfail(
    strict=True,
    reason="#110 decision rule broken: run-to-run Δ_noise ≡ 0 under the C-119 determinism fix",
)
def test_noise_band_is_within_run_bootstrap_not_run_to_run():
    """HARD (P2): #110's decision rule derives Δ_noise from TWO same-seed runs. But C-119 made
    same-seed `--saved` runs BIT-IDENTICAL — proven 2026-06-15 (78/78 y_pred np.array_equal,
    PREDICTIONS IDENTICAL: True). So two 8-sample runs ⇒ Δ_noise ≡ 0 ⇒ a degenerate noise floor
    ⇒ coords 'win' on ANY nonzero improvement (false-positive risk). The noise band must come from
    mcr_readout's WITHIN-run bootstrap CI (already computed), not a run-to-run diff. Flip #110, then
    this xfail turns xpass."""
    raise AssertionError(
        "#110 must use mcr_readout's within-run bootstrap CI as the noise band; "
        "run-to-run difference is identically 0 under determinism."
    )


@pytest.mark.skip(
    reason="runtime gate — cannot unit-test; verify with one real 8-sample run before trusting 'ready'"
)
def test_8sample_run_completes_without_oom():
    """SOFT (P3): 8 samples is interpolated between 3 (completes) and 16 (OOM-killed at 16.6 GB,
    C-116/#124); the 8-sample eval footprint on a 32 GB box is unverified. 'Ready to run two
    8-sample runs' assumes it fits. Verify empirically (the #110 acceptance gate)."""
    ...
