"""
Falsification test stubs for claim:
"The main cause of structural sensitivity is the curriculum-based
importance sampling."

Generated by /falsify audit on 2026-05-26

Three soft falsifications found. The claim overstates importance
sampling's primacy — the shrinkage zero-gate and weight-update
feedback loop are equally significant mechanisms.

These tests encode the falsifying observations.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
import pytest

MODELS_ROOT = Path(__file__).resolve().parents[1].parent / "views-models" / "models"
PA_PARQUET = MODELS_ROOT / "purple_alien" / "data" / "raw" / "calibration_viewser_df.parquet"
BS_PARQUET = (
    MODELS_ROOT / "bright_starship" / "data" / "raw" / "calibration_datafactory_df.parquet"
)
EVENT_COLS = ["lr_ged_sb", "lr_ged_ns", "lr_ged_os"]

CONFIG = {
    "time_col": "month_id",
    "id_col": "priogrid_gid",
    "spatial_cols": ["row", "col"],
    "identity_cols": ["month_id", "priogrid_gid", "c_id", "row", "col"],
    "features": ["lr_ged_sb", "lr_ged_ns", "lr_ged_os"],
    "index_names": ["month_id", "priogrid_gid"],
    "input_channels": 3,
    "row_offset": 87,
    "col_offset": 310,
    "height": 180,
    "width": 180,
    "window_dim": 32,
    "np_seed": 4,
    "total_lessons": 150,
    "windows_per_lesson": 3,
    "max_ratio": 0.95,
    "min_ratio": 0.05,
    "slope_ratio": 0.75,
    "roof_ratio": 0.7,
    "min_events": 5,
    "steps": list(range(1, 37)),
    "transformations": {
        "log1p": ["lr_ged_sb", "lr_ged_ns", "lr_ged_os"],
        "asinh": [],
        "identity": [],
    },
    "derivations": {
        "binary": [
            {"from": "lr_ged_sb", "to": "by_sb_best", "threshold": 0},
            {"from": "lr_ged_ns", "to": "by_ns_best", "threshold": 0},
            {"from": "lr_ged_os", "to": "by_os_best", "threshold": 0},
        ],
    },
}


def _skip_if_no_data():
    if not PA_PARQUET.exists() or not BS_PARQUET.exists():
        pytest.skip("Calibration parquets not available")


def _build_volumes():
    from views_hydranet.utils.data_fetcher import DataFetcher
    from views_hydranet.utils.volume_handler import VolumeHandler

    _skip_if_no_data()

    dfs = {}
    for label, path in [("pa", PA_PARQUET), ("bs", BS_PARQUET)]:
        df = pd.read_parquet(path).reset_index()
        df = df.sort_values(["month_id", "priogrid_gid"])
        df = df[df["priogrid_gid"] > 0].copy()
        df = DataFetcher.apply_blueprint(df, CONFIG)
        for col in EVENT_COLS:
            df[col] = np.log1p(df[col])
        dfs[label] = VolumeHandler.from_df(df, CONFIG)
    return dfs["pa"], dfs["bs"]


def test_falsify_g1_shrinkage_zero_gate():
    """
    Probe G1 (Category C — Boundary): Shrinkage loss as independent amplifier.

    Finding: With a=258, c=0.001, the shrinkage loss acts as a binary
    zero-gate (log1p(1) = 0.693, 693x above the cliff). 69.1% of cells
    that differ between PA and BS have one side at zero and the other
    nonzero — they experience full gradient bifurcation (loss=0 vs
    loss≈MSE) regardless of which spatial patch the sampler selects.

    Severity: Soft falsification.

    Expected: If importance sampling were truly the MAIN cause of
    sensitivity, non-sampling amplifiers like the shrinkage zero-gate
    should affect < 30% of differing cells. 69.1% is a dominant
    co-factor that operates independently.
    """
    pa_vh, bs_vh = _build_volumes()

    steps_len = len(CONFIG["steps"])
    pa_train = pa_vh.slice_time(0, pa_vh.data.shape[pa_vh.get_axis_idx("T")] - steps_len)
    bs_train = bs_vh.slice_time(0, bs_vh.data.shape[bs_vh.get_axis_idx("T")] - steps_len)

    feature_indices = [pa_train.channel_map.index(f) for f in CONFIG["features"]]

    pa_feat = pa_train.data[..., feature_indices].astype(np.float64)
    bs_feat = bs_train.data[..., feature_indices].astype(np.float64)

    diff_mask = np.abs(pa_feat - bs_feat) > 1e-7
    total_differing = np.count_nonzero(diff_mask)

    pa_zero = pa_feat == 0.0
    bs_zero = bs_feat == 0.0
    cross_cliff = diff_mask & ((pa_zero & ~bs_zero) | (~pa_zero & bs_zero))
    n_cross_cliff = np.count_nonzero(cross_cliff)

    pct_cross_cliff = 100.0 * n_cross_cliff / total_differing if total_differing > 0 else 0

    assert pct_cross_cliff < 30.0, (
        f"{pct_cross_cliff:.1f}% of differing cells ({n_cross_cliff}/{total_differing}) "
        f"straddle the shrinkage zero-gate (one zero, one nonzero). "
        f"These experience full gradient bifurcation regardless of sampling "
        f"strategy. The shrinkage loss is a dominant co-factor, not secondary."
    )


def test_falsify_g3_mechanism_a_prevalence():
    """
    Probe G3 (Category E — Consistency): Mechanism A is more prevalent
    than importance sampling spatial divergence.

    Finding: Mechanism A (value divergence in identical windows) affects
    245/450 = 54.4% of steps. Mechanism B (importance sampling spatial
    divergence) affects 205/450 = 45.6%. The claim that importance
    sampling is the "main cause" contradicts the evidence that the
    more prevalent mechanism is pure value divergence.

    Severity: Soft falsification.

    Expected: If importance sampling is the main cause, mechanism B
    should affect more steps than mechanism A.
    """
    from views_hydranet.utils.curriculum import CurriculumLearner

    pa_vh, bs_vh = _build_volumes()
    pa_cl = CurriculumLearner(CONFIG, pa_vh)
    bs_cl = CurriculumLearner(CONFIG, bs_vh)

    steps_len = len(CONFIG["steps"])
    pa_train = pa_vh.slice_time(0, pa_vh.data.shape[pa_vh.get_axis_idx("T")] - steps_len)
    bs_train = bs_vh.slice_time(0, bs_vh.data.shape[bs_vh.get_axis_idx("T")] - steps_len)

    total_steps = CONFIG["total_lessons"] * CONFIG["windows_per_lesson"]
    n_identical = 0
    n_divergent = 0

    for step in range(total_steps):
        pa_subj, pa_thresh = pa_cl.get_lesson(step)
        bs_subj, bs_thresh = bs_cl.get_lesson(step)

        pa_idx = pa_train.channel_map.index(pa_subj)
        bs_idx = bs_train.channel_map.index(bs_subj)

        pa_activity = np.count_nonzero(pa_train.data[..., pa_idx], axis=0)
        bs_activity = np.count_nonzero(bs_train.data[..., bs_idx], axis=0)

        pa_cells = set(map(tuple, np.argwhere(pa_activity >= pa_thresh)))
        bs_cells = set(map(tuple, np.argwhere(bs_activity >= bs_thresh)))

        if pa_cells == bs_cells:
            n_identical += 1
        else:
            n_divergent += 1

    assert n_divergent > n_identical, (
        f"Mechanism B (spatial divergence from importance sampling) affects "
        f"{n_divergent}/{total_steps} steps ({100 * n_divergent / total_steps:.1f}%), "
        f"but mechanism A (value divergence) affects {n_identical}/{total_steps} "
        f"({100 * n_identical / total_steps:.1f}%) steps with identical windows. "
        f"Mechanism A is more prevalent — importance sampling is not the main cause."
    )


def test_falsify_g4_uniform_sampling_still_diverges():
    """
    Probe G4+G5 (Category H+B): Under uniform random sampling, value
    divergence persists at ~50.7% of windows.

    Finding: Importance sampling amplifies per-window divergence by 2.74x
    over uniform sampling. But under uniform sampling, 50.7% of windows
    STILL contain differing cells. Removing importance sampling reduces
    but does not eliminate sensitivity — the base chaotic dynamics
    (weight-update feedback over 150 lessons) persist.

    Severity: Soft falsification.

    Expected: If importance sampling is the MAIN cause, removing it
    (uniform sampling counterfactual) should reduce window-level
    divergence by > 10x (rendering it negligible). A 2.74x reduction
    means importance sampling is a significant factor but not the
    dominant one.
    """
    pa_vh, bs_vh = _build_volumes()

    steps_len = len(CONFIG["steps"])
    pa_train = pa_vh.slice_time(0, pa_vh.data.shape[pa_vh.get_axis_idx("T")] - steps_len)
    bs_train = bs_vh.slice_time(0, bs_vh.data.shape[bs_vh.get_axis_idx("T")] - steps_len)

    h_max = pa_train.data.shape[1]
    w_max = pa_train.data.shape[2]
    dim = CONFIG["window_dim"]

    feature_indices = [pa_train.channel_map.index(f) for f in CONFIG["features"]]

    rng = np.random.default_rng(4)
    total_steps = CONFIG["total_lessons"] * CONFIG["windows_per_lesson"]
    n_with_diffs = 0

    for _ in range(total_steps):
        r_anc = rng.integers(0, h_max)
        c_anc = rng.integers(0, w_max)
        r0 = int(np.clip(r_anc - rng.integers(0, dim), 0, h_max - dim))
        c0 = int(np.clip(c_anc - rng.integers(0, dim), 0, w_max - dim))

        pa_win = pa_train.data[:, r0 : r0 + dim, c0 : c0 + dim, :]
        bs_win = bs_train.data[:, r0 : r0 + dim, c0 : c0 + dim, :]

        feat_diff = np.abs(
            pa_win[..., feature_indices].astype(np.float64)
            - bs_win[..., feature_indices].astype(np.float64)
        )
        if np.any(feat_diff > 1e-7):
            n_with_diffs += 1

    pct_with_diffs = 100.0 * n_with_diffs / total_steps

    amplification = pct_with_diffs / 99.3 if pct_with_diffs > 0 else float("inf")

    assert amplification < 0.1, (
        f"Under uniform sampling, {pct_with_diffs:.1f}% of windows still "
        f"contain feature differences (vs ~99.3% with importance sampling). "
        f"Importance sampling concentrates divergence by only "
        f"{99.3 / pct_with_diffs:.1f}x — removing it does not eliminate the "
        f"base sensitivity. The weight-update feedback loop amplifies "
        f"value-level differences regardless of sampling strategy."
    )
