"""
Falsification test stubs for claim:
"All sampling_strategies have complete and meaningful test coverage."

Generated by /falsify audit on 2026-05-26

Four soft falsifications found:
  P1: Power-law tests lack discriminative power (3/4 pass with wrong formula)
  P2: Sigmoid threshold-recovery test never implemented
  P3: No integration test for non-threshold strategies through VolumeSampler
  P4: Config validator rejection path untested
"""

from __future__ import annotations

import numpy as np
import pytest

from views_hydranet.utils.sampling_strategies import (
    select_anchor_power_law,
    select_anchor_sigmoid,
    select_anchor_threshold,
)

# ---------------------------------------------------------------------------
# Fixtures (shared)
# ---------------------------------------------------------------------------
H, W = 16, 16
THRESHOLD = 50
MIN_EVENTS = 5


def _sample_n(fn, activity, threshold, min_events, config, n=1000, seed=42):
    rng = np.random.default_rng(seed)
    return [fn(activity, threshold, min_events, rng, config) for _ in range(n)]


def _count_quadrants(samples):
    counts = {"top_left": 0, "top_right": 0, "bot_left": 0, "bot_right": 0}
    for r, c in samples:
        if r < 8 and c < 8:
            counts["top_left"] += 1
        elif r < 8 and c >= 8:
            counts["top_right"] += 1
        elif r >= 8 and c < 8:
            counts["bot_left"] += 1
        else:
            counts["bot_right"] += 1
    return counts


# ---------------------------------------------------------------------------
# P1: Power-law discriminative power
# ---------------------------------------------------------------------------
class TestFalsifyP1PowerLawDiscriminativePower:
    """
    Probe 1 (Category H — Mutation): Power-law test discriminative power.

    Finding: 3 of 4 TestPowerLaw tests (concentration, medium_activity_included,
    seed_reproducibility) pass even when select_anchor_power_law is replaced
    with Boltzmann logic. Only alpha_increases_concentration catches the
    mutation because Boltzmann ignores sampling_alpha.

    Tests that cannot distinguish the correct implementation from a wrong
    one provide false confidence.

    Severity: Soft falsification.

    Fix: Add a test that verifies the power-law formula's defining property —
    that the probability ratio between two cells equals the activity ratio
    raised to the power alpha.
    """

    def test_power_law_ratio_matches_formula(self):
        """p(cell_a) / p(cell_b) ≈ (activity_a / activity_b)^alpha.

        With only two eligible cells, the probability ratio is fully
        determined by the formula. This test would FAIL if the implementation
        used Boltzmann (exp(activity/tau)) instead of power-law (activity^alpha).
        """
        activity = np.zeros((H, W), dtype=np.int64)
        activity[0, 0] = 100
        activity[1, 1] = 50

        alpha = 2.0
        cfg = {"sampling_alpha": alpha}
        n = 10000
        samples = _sample_n(select_anchor_power_law, activity, THRESHOLD, MIN_EVENTS, cfg, n=n)

        hits_100 = sum(1 for r, c in samples if (r, c) == (0, 0))
        hits_50 = sum(1 for r, c in samples if (r, c) == (1, 1))

        assert hits_50 > 0, "Both cells should be sampled"

        observed_ratio = hits_100 / hits_50
        expected_ratio = (100 / 50) ** alpha  # 4.0

        assert abs(observed_ratio - expected_ratio) < 1.5, (
            f"Power-law ratio should be ~{expected_ratio:.1f}, "
            f"got {observed_ratio:.1f} ({hits_100}/{hits_50})"
        )


# ---------------------------------------------------------------------------
# P2: Sigmoid threshold recovery
# ---------------------------------------------------------------------------
class TestFalsifyP2SigmoidThresholdRecovery:
    """
    Probe 2 (Category E — Omission): Sigmoid threshold recovery.

    Finding: The plan specified a test that sigmoid with steepness→large
    should recover hard-threshold behaviour. This test was never implemented.
    Threshold recovery is the sigmoid strategy's key correctness property —
    it must degenerate to the threshold strategy in the limit.

    Severity: Soft falsification.

    Fix: Implement the threshold recovery test.
    """

    def test_sigmoid_high_steepness_recovers_threshold(self):
        """Sigmoid with very high steepness should behave like hard threshold.

        With steepness=100, cells well above threshold get ~uniform probability
        and cells well below threshold get ~0 probability, matching the
        threshold strategy's behaviour.
        """
        activity = np.zeros((H, W), dtype=np.int64)
        activity[0:8, 0:8] = 100  # well above threshold
        activity[0:8, 8:16] = 30  # well below threshold
        activity[8:16, 0:8] = 3  # below min_events

        cfg_sigmoid = {"sampling_steepness": 100.0}
        n = 2000

        samples_sigmoid = _sample_n(
            select_anchor_sigmoid, activity, THRESHOLD, MIN_EVENTS, cfg_sigmoid, n=n
        )
        samples_threshold = _sample_n(
            select_anchor_threshold, activity, THRESHOLD, MIN_EVENTS, {}, n=n
        )

        counts_sigmoid = _count_quadrants(samples_sigmoid)
        counts_threshold = _count_quadrants(samples_threshold)

        assert counts_sigmoid["top_left"] == n, (
            f"High-steepness sigmoid should select only above-threshold cells, "
            f"got {counts_sigmoid}"
        )
        assert counts_threshold["top_left"] == n, (
            f"Threshold baseline check failed, got {counts_threshold}"
        )


# ---------------------------------------------------------------------------
# P3: Integration test for non-threshold strategy
# ---------------------------------------------------------------------------
class TestFalsifyP3NonThresholdIntegration:
    """
    Probe 3 (Category E — Integration): Non-threshold strategy through VolumeSampler.

    Finding: test_volume_sampler.py only uses sampling_strategy="threshold".
    No test verifies that a non-default strategy (power_law, boltzmann, sigmoid)
    works end-to-end through VolumeSampler.__init__ → _generate_window → get_batch.

    Severity: Soft falsification.

    Fix: Add an integration test that runs VolumeSampler with each non-default strategy.
    """

    def test_power_law_through_volume_sampler(self):
        """VolumeSampler with sampling_strategy='power_law' produces valid batch."""
        from views_hydranet.utils.volume_handler import VolumeHandler
        from views_hydranet.utils.volume_sampler import VolumeSampler

        T, H, W, C = 10, 8, 8, 3
        rng = np.random.RandomState(42)
        data = rng.rand(T, H, W, C).astype(np.float32)
        channel_map = ["month_id", "priogrid_gid", "value"]

        handler = VolumeHandler(
            data=data,
            axes=("T", "H", "W", "C"),
            channel_map=channel_map,
            time_col="month_id",
            id_col="priogrid_gid",
            spatial_cols=("row", "col"),
        )

        cfg = {
            "window_dim": 4,
            "windows_per_lesson": 3,
            "np_seed": 42,
            "steps": [1, 2],
            "sampling_strategy": "power_law",
            "sampling_alpha": 1.5,
            "min_events": 1,
        }
        sampler = VolumeSampler(handler, cfg)
        batch, qualified = sampler.get_batch("value", threshold=1, batch_size=2)

        assert len(batch) == 2, f"Expected 2 windows, got {len(batch)}"
        for i, window in enumerate(batch):
            assert window.shape[1] == 4, f"Window {i} H mismatch"
            assert window.shape[2] == 4, f"Window {i} W mismatch"

    def test_boltzmann_through_volume_sampler(self):
        """VolumeSampler with sampling_strategy='boltzmann' produces valid batch."""
        from views_hydranet.utils.volume_handler import VolumeHandler
        from views_hydranet.utils.volume_sampler import VolumeSampler

        T, H, W, C = 10, 8, 8, 3
        rng = np.random.RandomState(42)
        data = rng.rand(T, H, W, C).astype(np.float32)
        channel_map = ["month_id", "priogrid_gid", "value"]

        handler = VolumeHandler(
            data=data,
            axes=("T", "H", "W", "C"),
            channel_map=channel_map,
            time_col="month_id",
            id_col="priogrid_gid",
            spatial_cols=("row", "col"),
        )

        cfg = {
            "window_dim": 4,
            "windows_per_lesson": 3,
            "np_seed": 42,
            "steps": [1, 2],
            "sampling_strategy": "boltzmann",
            "sampling_temperature": 10.0,
            "min_events": 1,
        }
        sampler = VolumeSampler(handler, cfg)
        batch, qualified = sampler.get_batch("value", threshold=1, batch_size=2)

        assert len(batch) == 2, f"Expected 2 windows, got {len(batch)}"

    def test_sigmoid_through_volume_sampler(self):
        """VolumeSampler with sampling_strategy='sigmoid' produces valid batch."""
        from views_hydranet.utils.volume_handler import VolumeHandler
        from views_hydranet.utils.volume_sampler import VolumeSampler

        T, H, W, C = 10, 8, 8, 3
        rng = np.random.RandomState(42)
        data = rng.rand(T, H, W, C).astype(np.float32)
        channel_map = ["month_id", "priogrid_gid", "value"]

        handler = VolumeHandler(
            data=data,
            axes=("T", "H", "W", "C"),
            channel_map=channel_map,
            time_col="month_id",
            id_col="priogrid_gid",
            spatial_cols=("row", "col"),
        )

        cfg = {
            "window_dim": 4,
            "windows_per_lesson": 3,
            "np_seed": 42,
            "steps": [1, 2],
            "sampling_strategy": "sigmoid",
            "sampling_steepness": 1.0,
            "min_events": 1,
        }
        sampler = VolumeSampler(handler, cfg)
        batch, qualified = sampler.get_batch("value", threshold=1, batch_size=2)

        assert len(batch) == 2, f"Expected 2 windows, got {len(batch)}"


# ---------------------------------------------------------------------------
# P4: Config validator rejection path
# ---------------------------------------------------------------------------
class TestFalsifyP4ConfigValidatorRejection:
    """
    Probe 4 (Category B — Boundary): Config validator rejection path.

    Finding: validate_sampling_strategy in config_initializer.py raises
    ValueError for unregistered strategies, but no test exercises this path.

    Severity: Soft falsification.

    Fix: Add test that invalid sampling_strategy raises ValueError.
    """

    def test_invalid_sampling_strategy_raises(self):
        """HydraNetConfig with unknown sampling_strategy raises ValueError."""
        from pydantic import ValidationError

        from views_hydranet.utils.config_initializer import HydraNetConfig

        with pytest.raises(ValidationError, match="not registered"):
            HydraNetConfig(sampling_strategy="nonexistent_strategy")
