"""A-S2 (#169): legacy emit-math parity anchor (ADR-067).

Re-runs the real ``HydraNetInference._emit_magnitude`` on the fixed synthetic input stored in the
golden fixture and asserts **byte-identity** against the recorded output for every
``output_distribution`` value. This is the reference the strangler-fig wiring (A-S6..A-S8) must
not break: once a branch delegates to a family, its emit output must still equal this anchor.

The golden is regenerated by ``build_emit_parity_anchor.py`` in the same dossier folder.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

torch = pytest.importorskip("torch")

_GOLDEN = (
    Path(__file__).resolve().parents[2]
    / "reports"
    / "2026-07-20_distributional_head_dossier"
    / "parity_anchor"
    / "emit_parity_golden.json"
)

# output_distribution -> which recorded sidecar params its branch reads
_USES_THETA = {"hurdle_nb"}
_USES_SIGMA = {"hurdle_lognormal"}


def _load():
    data = json.loads(_GOLDEN.read_text())
    inp = data["inputs"]
    tensors = {k: torch.tensor(v, dtype=torch.float32) for k, v in inp.items()}
    return data["outputs"], tensors


_DISTRIBUTIONS = [
    "standard",
    "hurdle_nb",
    "hurdle_lognormal",
    "hurdle_shrinkage",
    "dense_nb",
    "quantile",
]


@pytest.mark.parametrize("name", _DISTRIBUTIONS)
def test_emit_magnitude_matches_parity_anchor_byte_for_byte(name):
    from types import SimpleNamespace

    from views_hydranet.utils.hydranet_inference import HydraNetInference

    outputs, t = _load()
    assert name in outputs, f"golden fixture missing '{name}' — regenerate the anchor"

    stub = SimpleNamespace(
        output_distribution=name,
        hurdle_theta=t["theta"] if name in _USES_THETA else None,
        lognormal_sigma=t["sigma"] if name in _USES_SIGMA else None,
    )
    emitted = HydraNetInference._emit_magnitude(stub, t["reg"], t["prob"])
    expected = torch.tensor(outputs[name], dtype=torch.float32)
    assert torch.equal(emitted, expected), (
        f"emit drift for output_distribution='{name}': the anchor no longer matches "
        f"_emit_magnitude. If this is an intended change, regenerate the golden and review."
    )
