#!/usr/bin/env python3
"""
Generates docs/ADRs/README.md from the actual directory contents.

Run from the repo root or from docs/ADRs/:
    python docs/ADRs/generate_readme.py

The README is derived, not maintained. This script is the single source
of truth for the ADR index. Run it after adding, moving, or archiving ADRs.
"""

import re
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
ACTIVE_DIR = SCRIPT_DIR / "active"
PROPOSED_DIR = SCRIPT_DIR / "proposed"
ARCHIVE_DIR = SCRIPT_DIR / "archive"
README_PATH = SCRIPT_DIR / "README.md"

CONSTITUTIONAL_RANGE = range(0, 10)  # 000-009


def extract_adr_info(filepath: Path) -> tuple[str, str, str]:
    """Extract (number, title, relative_path) from an ADR file.

    Reads the first line and parses '# ADR NNN: Title' format.
    Falls back to humanizing the filename if the header doesn't match.
    """
    rel_path = filepath.relative_to(SCRIPT_DIR).as_posix()

    # Extract number from filename (e.g., '020_multi_task_output_topology.md' -> '020')
    match = re.match(r"(\d{3})_", filepath.name)
    if not match:
        # Handle files like 'proposed_023_...'
        match = re.search(r"(\d{3})_", filepath.name)
    if not match:
        return ("???", filepath.stem, rel_path)

    number = match.group(1)

    # Read first line for title
    try:
        first_line = filepath.read_text().split("\n")[0].strip()
    except Exception:
        first_line = ""

    # Parse '# ADR NNN: Title' or '# Title'
    title_match = re.match(r"#\s+(?:ADR\s+\d+:\s*)?(.+)", first_line)
    if title_match:
        title = title_match.group(1).strip()
    else:
        # Humanize filename: '020_multi_task_output_topology' -> 'Multi Task Output Topology'
        title = filepath.stem.split("_", 1)[-1].replace("_", " ").title()

    return (number, title, rel_path)


def scan_directory(directory: Path) -> list[tuple[str, str, str]]:
    """Scan a directory for ADR markdown files, return sorted list of (number, title, path)."""
    if not directory.exists():
        return []
    entries = []
    for f in sorted(directory.glob("*.md")):
        if f.name == "README.md":
            continue
        entries.append(extract_adr_info(f))
    return entries


def generate_readme() -> str:
    """Generate the full README content."""
    active = scan_directory(ACTIVE_DIR)
    proposed = scan_directory(PROPOSED_DIR)
    archive = scan_directory(ARCHIVE_DIR)

    constitutional = [(n, t, p) for n, t, p in active if int(n) in CONSTITUTIONAL_RANGE]
    project = [(n, t, p) for n, t, p in active if int(n) not in CONSTITUTIONAL_RANGE]

    lines = []
    lines.append("# Architectural Decision Records (ADRs)")
    lines.append("")
    lines.append(
        "This directory contains the Architectural Decision Records (ADRs) "
        "for the HydraNet project. Records are organized by their lifecycle "
        "status to ensure the codebase remains governed and traceable."
    )
    lines.append("")
    lines.append("<!-- This file is generated by generate_readme.py. Do not edit manually. -->")
    lines.append("")
    lines.append("## Directory Structure")
    lines.append("")
    lines.append(
        '- **[`active/`](./active/)**: The current "Law of the Land." '
        "Accepted, implemented, and verified."
    )
    lines.append(
        "- **[`proposed/`](./proposed/)**: Emerging specifications "
        "under review or awaiting implementation."
    )
    lines.append(
        "- **[`archive/`](./archive/)**: Legacy records, superseded "
        "specifications, and rejected proposals."
    )
    lines.append(
        "- **[`templates/`](./templates/)**: Constitutional ADR templates from base_docs."
    )
    lines.append("")
    lines.append("---")
    lines.append("")

    # Active — Constitutional
    lines.append("## [Active (The Law)](./active/)")
    lines.append("")
    lines.append("### Constitutional ADRs (000-009)")
    lines.append("")
    lines.append(
        "Governance foundation adopted from base_docs. "
        "These define HOW the project governs itself."
    )
    lines.append("")
    for number, title, path in constitutional:
        lines.append(f"- **[{number}]({path})**: {title}")
    lines.append("")

    # Active — Project-specific
    lines.append("### Project-Specific ADRs (010+)")
    lines.append("")
    lines.append("Architectural decisions specific to the HydraNet system.")
    lines.append("")
    for number, title, path in project:
        lines.append(f"- **[{number}]({path})**: {title}")
    lines.append("")

    # Proposed
    lines.append("## [Proposed (Emerging)](./proposed/)")
    lines.append("")
    if proposed:
        for number, title, path in proposed:
            lines.append(f"- **[{number}]({path})**: {title}")
    else:
        lines.append("No proposed ADRs.")
    lines.append("")

    # Archive
    lines.append("## [Archive (Historical)](./archive/)")
    lines.append("")
    if archive:
        for number, title, path in archive:
            lines.append(f"- **[{number}]({path})**: {title}")
    else:
        lines.append("No archived ADRs.")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("## Usage & Quality")
    lines.append("")
    lines.append(
        "Every new ADR must follow the "
        "[ADR Template](./templates/adr_template.md) and satisfy "
        "the quality criteria defined in "
        "**[ADR 000](./active/000_standard_for_adrs.md)**."
    )
    lines.append("")

    return "\n".join(lines)


if __name__ == "__main__":
    content = generate_readme()
    README_PATH.write_text(content)
    print(f"Generated {README_PATH} ({len(content)} bytes)")
